### ISSUE TITLE
PHP Build Sample

### ISSUE THREAD

**Issue by yohanswanepoel** [redhat-developer-demos/containers#11]
Samples should include:

Documentation
Test and usage instructions
Tested on OpenShift
Highlight differences between OCP and non-best practice builds *optional

**Comment by cuppett** [comment]
A common PHP sample covering webapps actually has two containers, the web server frontend (for HTML/JS/CSS) and then the FPM backend for the PHP files. See this article: [Deploying a Performant PHP Application on Kubernetes with Rancher](https://rancher.com/blog/2020/deploy-php-application). However, there's another interesting wrinkle setting a web server up to talk to FPM; choosing a unix socket or port and whether to deploy them together in a single pod or as separate services. Choosing the right deployment style depends on your workload.

The Red Hat S2I runtime uses a single container with apache + mod_php which is ideal for API-only based deployments (without a mix of HTML/JS/CSS). It also has the right "builder" concept where it invokes composer to install app dependencies [[1]](https://github.com/sclorg/s2i-php-container/blob/master/7.3/s2i/bin/assemble#L20-L58) and tries to do some dynamic configuration via container memory math [[2]](https://github.com/sclorg/s2i-php-container/blob/master/7.3/s2i/bin/run#L39-L52). Apache can be configured in the PHP-FPM based topology as well.

There's three different permutations of the above... Comprehensively, we'd differentiate them all as they are built for purpose and incorporate the composer aspect into the build step. Do we have a target style for this?

**Comment by yohanswanepoel** [comment]
This is possibly good background to go into the Readme for the PHP example. 

I think for these examples keeping it as simple as possible initially would be good so starting with a single Apache + mod_php example. We can then build it out to use FPM. The challenge with FPM as you stated it creates dependencies that need to be managed.
