### ISSUE TITLE
Builds should be encouraged with Buildah

### ISSUE THREAD

**Issue by ArangoGutierrez** [redhat-developer-demos/containers#13]
I see our first example `Python` has build examples pointing to `podman build` but as part of container good practices we should encourage users to build their images with Buildah and podman for running them

**Comment by yohanswanepoel** [comment]
Happy to change. If I can ask what is the benefit of building with buildah over podman?

**Comment by ArangoGutierrez** [comment]
podman uses buildah underneath for builds (same code logic), but with buildah developers have extra tools for building images, is more flexible by allowing developers not only to depend on a Dockerfile, but source files, and even bash scripts

**Comment by yohanswanepoel** [comment]
Updated readme files and also the initial page.
