### ISSUE TITLE
Go Build Sample

### ISSUE THREAD

**Issue by yohanswanepoel** [redhat-developer-demos/containers#5]
Samples should include:

Documentation
Test and usage instructions
Tested on OpenShift
Highlight differences between OCP and non-best practice builds *optional

**Comment by yohanswanepoel** [comment]
Thanks mate. Quick question, more for my understanding. Does that build work on OpenShift without changing the user to non-root? If so is it the UBI that makes it work? If not, then the container build file may need to be tweaked.

**Comment by ArangoGutierrez** [comment]
Yes this build example is taken from an operator I maintain, it can be build via BuildConfigs, and the image is constantly build by our ART team

**Comment by yohanswanepoel** [comment]
Awesome thank you.
